### PR TITLE
enable ibm-platform-api-operator by default

### PR DESCRIPTION
**Pull request by cheewaio**
**What this PR does / why we need it**:
enable ibm-platform-api-operator by default

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cheewaio** [comment]
> @cheewaio Please update CSV as well

Thanks..added to csv

**Comment by chenzhiwei** [comment]
@horis233 I think we can enable all of them now, could you create a PR to enable them all?

**Comment by horis233** [comment]
@chenzhiwei Yes, I will open a PR to enable all the operators.

**Comment by horis233** [comment]
@cheewaio @chenzhiwei I open a PR to enable all the services

**Pull request closed without merging**
