### PR TITLE
Change channel of ingress operator to stable

### PR DESCRIPTION
**Pull request by liqlin2015**
For Common Services 3.3.0 release need to move to stable-v1
channel.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by DanielXLee** [comment]
@morvencao Could you take a look at it, why the prow check hang?

**Comment by horis233** [comment]
@DanielXLee That is because there is a `need-ok-to-test` label. Maybe @liqlin2015 doesn't bind the public Github account with the GHE account.

**Comment by morvencao** [comment]
The PRs raised by non-member will need `ok-to-test` label to start the prow jobs.

**Pull request merged**
