### PR TITLE
add complete err check

### PR DESCRIPTION
**Pull request by Daniel-Fan**
It is the cherry-pick of https://github.com/IBM/operand-deployment-lifecycle-manager/pull/659

Let's hold it until the release of 3.7.3

### CODE REVIEW

**Comment by Daniel-Fan** [comment]
It is ready to merge, since 3.7.3 has been released.

**Comment by horis233** [comment]
@Daniel-Fan Please bump the operator version first before merging this PR

**Comment by Daniel-Fan** [comment]
@horis233 
Sure, the PR for bumping version is open https://github.com/IBM/operand-deployment-lifecycle-manager/pull/666

**Review by horis233 — APPROVED** [review]
/lgtm

**Pull request merged**
