### PR TITLE
Add unit test for controllers

### PR DESCRIPTION
**Pull request by horis233**
**What this PR does / why we need it**:

This PR adds basic unit tests for OperandConfig OperandRegistry and OperandRequest controller.
Because ODLM depends on OLM, thus the unit test has limits on checking all the functions, we still need e2e test to cover more testing cases.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by horis233** [comment]
I update the test-infra by this PR https://github.com/IBM/test-infra/pull/232. It is not updated yet.

**Comment by DanielXLee** [comment]
@horis233 maybe need to create a new PR, for this PR if amd64 pass, will can force merge it.

**Review by DanielXLee — APPROVED** [review]
/lgtm

**Comment by horis233** [comment]
@DanielXLee I force push to update this PR. Could you please review it again?

**Pull request merged**
