### PR TITLE
implement channel fallback in catalog discovery

### PR DESCRIPTION
**Pull request by Daniel-Fan**
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64549

### CODE REVIEW

**Review by YCShen1010 — APPROVED** [review]
/lgtm

**Comment by Daniel-Fan** [comment]
The test case is failed due to missing apiservice for PackageManifest, will need to set the cluster properly before the testing.
```
no matches for kind "PackageManifest" in version "packages.operators.coreos.com/v1"
```

Merge the PR for now to catch up the dcut.

**Pull request merged**
