### PR TITLE
added bitscuit to OWNERS

### PR DESCRIPTION
**Pull request by bitscuit**
**What this PR does / why we need it**:
Adding new team member to repo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Comment by Daniel-Fan** [comment]
@horis233 
I believe this PR needs the approval of you.

I will add myself to the OWNERS after this PR is merged in order to avoid conflict.

**Comment by horis233** [comment]
@bitscuit please add @Daniel-Fan and remove jinchun-dev

**Review by horis233 — APPROVED** [review]
/lgtm

**Pull request merged**
