### PR TITLE
Porting protobuf fix to EUS

### PR DESCRIPTION
**Pull request by bitscuit**
**What this PR does / why we need it**:
Fix gogo/protobuf vulnerability https://github.com/IBM/operand-deployment-lifecycle-manager/pull/594

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Comment by horis233** [comment]
Test fail is because the travis api is not available, will update it in the following PR. I will force merge this one.

**Pull request merged**
