### PR TITLE
Update go to 1.20.5

### PR DESCRIPTION
**Pull request by bluzarraga**

### CODE REVIEW

**Comment by bluzarraga** [comment]
prow is failing with:
```
 Step 6/20 : RUN go mod download
 ---> Running in d7882463a58f
runtime/cgo: pthread_create failed: Operation not permitted
              
SIGABRT: abort
```
But the only change is going from go 1.20.4 to 1.20.5 so this should not be an issue

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Comment by bluzarraga** [comment]
failed due to 
```
 Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
error: deployment "olm-operator" exceeded its progress deadline
Makefile:200: recipe for target 'kind-start' failed
make: *** [kind-start] Error 1 
```
This should resolve with a retest or two

**Comment by Daniel-Fan** [comment]
I believe it is due to the kind cluster update, and ODLM e2e test case is out of dated.
We have a ticket to track the update progress. https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59167

I will merge the PR for now.

**Pull request merged**
